### ISSUE TITLE
Provide db migration

### ISSUE THREAD

**Issue by Sebobo** [patriceckhart/NeosRulez.Acl#1]
`doctrine:update` shouldn't be used to set the db to the correct state.

Instead it is highly recommended to provide a [db migration](https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Persistence.html#schema-management).

**Comment by patriceckhart** [comment]
@Sebobo Thanks, I'll adjust that.

**Comment by Sebobo** [comment]
I guess this is still not solved?
Do you want a PR?

**Comment by patriceckhart** [comment]
@Sebobo Thank you! Sorry, I was no longer using the package. I will submit the migration later, unless you already have one ready?

**Comment by Sebobo** [comment]
Created one
